### ISSUE TITLE
Backdoor Detected, but Cant find it

### ISSUE THREAD

**Issue by BadWorksFun** [SnowboiTheGr8/backdoor-buster#2]
> Backdoor Blocked: scriptenforcer.net - find the source of this attempt below
stack traceback:
	addons/backdoor-buster-master/lua/autorun/!sh_backdoor-buster.lua:82: in function 'http'
	addons/backdoor-buster-master/lua/autorun/!sh_backdoor-buster.lua:92: in function 'onsuccess'

I cant find the said file in here
	lua/includes/modules/http.lua:29: in function <lua/includes/modules/http.lua:25>

**Comment by drizmans** [comment]
Can't reproduce, scan your server files for the string "scriptenforcer.net"
