### ISSUE TITLE
updated link down

### ISSUE THREAD

**Issue by sh0tx420** [SnowboiTheGr8/backdoor-buster#5]
wayback machine didn't archive the thing lol

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
I found an alternate url, but its not what you think lol :c
https://web.archive.org/web/20190407114438mp_/https://forum.facepunch.com/gmodgd/btdjz/Backdoor-Scanner/1/

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
So basically this code here is what we got, better than nothing o:
